name: Sync to Personal Repository
on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Push to personal repository
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Add remote for personal repository
          git remote add personal https://${PERSONAL_TOKEN}@github.com/thomasaugot/dosxdos_web_2.0_frontend.git
          
          # Push to personal repository (force to ensure sync)
          git push personal HEAD:main --force
